---
- name: Install Python3
  ansible.builtin.yum:
    name: 
      - python3
      - python3-pip
    state: present

- name: MySql module deps
  ansible.builtin.yum:
    name: 
      - gcc
      - python3-devel
      - mariadb105
      - mariadb105-devel
      - pkgconfig 
    state: present

- name: Install mysqlclient
  ansible.builtin.pip:
    name: 
      - mysqlclient
    state: present
    executable: /usr/bin/pip3

- name: Copy SQL file to target host
  ansible.builtin.copy:
    src: ../backend/create_database.sql
    dest: /tmp/create_database.sql

- name: Create table
  mysql_db:
    name: "tododatabase"  # Specify the database name here
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: import
    target: /tmp/create_database.sql
