---
- name: Install MySQL client
  ansible.builtin.yum:
    name: mariadb105
    state: present
  when: ansible_facts.packages['mariadb105'] is not defined

- name: Install Python3
  ansible.builtin.yum:
    name: python3
    state: present

- name: Install pip for Python3
  ansible.builtin.yum:
    name: python3-pip
    state: present

- name: Install PyMySQL using pip
  ansible.builtin.pip:
    name: PyMySQL
    state: present

- name: Create table
  mysql_db:
    name: ""  # Specify the database name here
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: import
    target: ../backend/create_database.sql  # SQL script to create the table
  delegate_to: localhost
  environment:
    ANSIBLE_PYTHON_INTERPRETER: "/usr/bin/python3"

