---
- name: Install PyMySQL
  ansible.builtin.pip:
    name: pymysql
    state: present

- name: Create MySQL Database
  community.mysql.mysql_db:
    name: tododatabase
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: present

- name: Import SQL File
  community.mysql.mysql_db:
    name: tododatabase
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: import
    target: /tmp/create_database.sql

