---
- name: Install Python3
  ansible.builtin.yum:
    name: 
      - python3
      - python3-pip
    state: present

- name: Install PyMySQL using pip
  ansible.builtin.pip:
    name: 
      - PyMySQL
      - mysqlclient
    state: present
    executable: /usr/bin/pip3

- name: Create table
  mysql_db:
    name: ""  # Specify the database name here
    login_host: "{{ db_host }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    state: import
    target: ../backend/create_database.sql  # SQL script to create the table
