- hosts: ec2_instance
  become: yes
  tasks:
    - name: Install required packages (Java, Maven, Node.js, npm, Nginx)
      yum:
        name:
          - java-17-amazon-corretto
          - maven
          - nodejs
        state: present

    - name: Ensure npm is installed
      command: npm -v
      register: npm_version
      changed_when: false

    - name: Print npm version
      debug:
        msg: "npm version: {{ npm_version.stdout }}"

    - name: Move JAR file to deployment directory
      command: mv /home/ec2-user/backend/target/*.jar /opt/app.jar

    - name: Build Angular application
      command: npm run build --prod
      args:
        chdir: /home/ec2-user/frontend

    - name: Copy Angular build to Nginx directory
      command: cp -r /home/ec2-user/frontend/dist/* /usr/share/nginx/html/

    - name: Restart Java application
      systemd:
        name: java_app
        state: restarted
        enabled: yes
