---
- name: Install Docker
  ansible.builtin.yum:
    name: docker
    state: present

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to Docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: yes

- name: Pull Frontend image
  community.docker.docker_image:
    name: gyanendranagarro/frontend-app:"{{ app_version}}"
    source: pull

- name: Pull Backend image
  community.docker.docker_image:
    name: gyanendranagarro/backend-app:"{{backend_version}}"
    source: pull

- name: Stop Frontend
  community.docker.docker_container:
    name: frontend-app
    state: stopped
  ignore_errors: true

- name: Stop Backend
  community.docker.docker_container:
    name: backend-app
    state: stopped
  ignore_errors: true

- name: Create Docker Network
  community.docker.docker_network:
    name: app-network
    driver: bridge

- name: Run Frontend
  community.docker.docker_container:
    name: frontend-app
    image: gyanendranagarro/frontend-app:latest
    state: started
    restart_policy: always
    ports:
      - "4200:80"
    networks:
      - name: app-network

- name: Run backend
  community.docker.docker_container:
    name: backend-app
    image: gyanendranagarro/backend-app:latest
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
    networks:
      - name: app-network