name: Infra pipeline

on:
  push:
    branches:
      - master

permissions:
  id-token: write  

jobs:
  terraform:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.PIPELINE_ROLE }}
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Terraform plan
        run: |
          cd terraform
          terraform init
          terraform plan -out=tfplan

      - name: Terraplan apply
        run: |
          cd terraform
          terraform destroy --auto-approve


  ansible:
    name: Deploy build
    runs-on: ubuntu-latest
    needs: [terraform]
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Install Ansible AWS collection
        run: |
          ansible-galaxy collection install community.mysql
          ansible-galaxy collection install amazon.aws

      - name: Install AWS dependencies
        run: pip install boto3 botocore

