name: SonarQube Analysis Pipeline

on:
  workflow_run:
    workflows: ["Build_pipeline"]
    types:
      - completed

jobs:
  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache SonarQube Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Restore Compiled Java Classes
        uses: actions/download-artifact@v4
        with:
          name: backend-classes
          path: backend/restful-web-services/target/classes

      - name: Restore Backend Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage
          path: backend/restful-web-services/target/site/jacoco

      - name: Restore Frontend Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/todo/coverage

      - name: Run SonarQube Analysis
        run: |
          npx sonar-scanner -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Check SonarQube Quality Gate
        run: |
          sleep 10
          RESPONSE=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=fullapp_todoapp")

          echo "SonarQube Quality Gate Response:"
          echo "$RESPONSE" | jq .

          STATUS=$(echo "$RESPONSE" | jq -r .projectStatus.status)

          if [[ "$STATUS" != "OK" ]]; then
            echo "❌ Quality Gate Failed!"
            exit 1
          else
            echo "✅ Quality Gate Passed!"
          fi
        shell: bash
